SG-22646-shotgrid Shotgun instances has been replaced
shotgunsoftware/tk-framework-shotgunutils pull request #127
Opened 2021-05-28 21:12 UTC by zamu5

2021-05-31 12:29 UTC, jfboismenu requested changes

2021-05-31 12:29 UTC, jfboismenu commented on python/shotgun_model/shotgun_query_model.py
> +            "implemented for this ShotGridQueryModel subclass."
```suggestion
            "implemented for this ShotgunQueryModel subclass."
```

2021-05-31 12:29 UTC, jfboismenu commented on python/settings/user_settings.py
> +        self.__settings = QtCore.QSettings("ShotGrid Software", bundle.name)
```suggestion
        self.__settings = QtCore.QSettings("Shotgun Software", bundle.name)
```

If we did this, then users would lose their settings.

2021-06-01 16:03 UTC, jfboismenu approved these changes
Looks good to me, over to you @mathurf

2021-06-02 14:28 UTC, mathurf approved these changes
LGTM
Tested with Shotgunpanel and demo app

2021-06-02 14:28 UTC, merged